import { useRef } from "react"
import MainCard from "../components/MainCard"
import TopBar from "../components/TopBar"
import "../pages/main.css"
import "../pages/topbar.css"
import { useSelector } from "react-redux"
import toast from "react-hot-toast"

export default function Landing(){

    const googleToken = useSelector(state => state.googleToken)
    if(googleToken){
        console.log("Google Generated Token "+googleToken)
    }
    else{
        console.log("No Google Login Token Generated Yet!")
    }
    return(
        <div> 
        <TopBar/>
        <MainCard/>
        {googleToken && toast("Login Successful. You can see the Token Generated By Google In the CONSOLE.")}
        </div>
    )
}