import React, { useEffect, useMemo, useRef } from "react"
import MainCard from "../components/MainCard"
import TopBar from "../components/TopBar"
import "../pages/main.css"
import "../pages/topbar.css"
import { useSelector } from "react-redux"
import toast from "react-hot-toast"

function Landing(){

    const googleToken = useSelector(state => state.googleToken)
     
    let count = 0;
    useEffect(()=>{
        if(googleToken){
            if(count<1){
            console.log("Google Generated Token "+googleToken)
            toast("Login Successful. You can see the Token Generated By Google In the CONSOLE.")
            count++;
            }
        }
        else{
            console.log("No Google Login Token Generated Yet!")
        }
    }, [googleToken])
   
    return(
        <div> 
        <TopBar/>
        <MainCard/>
       
        </div>
    )
}

export default React.memo(Landing)